<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Str;
use DateTime;

class UserTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            [
                'name' =>  '川上 亜矢',
                'name_kana' =>  'かわかみ あや',
                'email' =>  'kawakamiaya@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '遠藤 隆志',
                'name_kana' =>  'えんどう たかし',
                'email' =>  'endo_takashi@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '菱田 宏幸',
                'name_kana' =>  'ひしだ ひろゆき',
                'email' =>  'hishidahiroyuki@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '島田 康雄',
                'name_kana' =>  'しまだ やすお',
                'email' =>  'shimadayasuo@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '柳 智司',
                'name_kana' =>  'やなぎ さとし',
                'email' =>  'yanagi61@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '豊泉 薫',
                'name_kana' =>  'とよいずみ かおる',
                'email' =>  'toyoizumikaoru@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '佐藤 紀子',
                'name_kana' =>  'さとう のりこ',
                'email' =>  'sato31@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '橋爪 正人',
                'name_kana' =>  'はしづめ まさと',
                'email' =>  'hashizume_618@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '竹市 悠介',
                'name_kana' =>  'たけいち ゆうすけ',
                'email' =>  'yusuke_takeichi@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '中川 健司',
                'name_kana' =>  'なかがわ けんじ',
                'email' =>  'nakagawa_226@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '山口 貴志',
                'name_kana' =>  'やまぐち たかし',
                'email' =>  'takashiyamaguchi@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '赤星 拓也',
                'name_kana' =>  'あかほし たくや',
                'email' =>  'akahoshi1126@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '広沢 美奈子',
                'name_kana' =>  'ひろさわ みなこ',
                'email' =>  'minako_hirosawa@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '谷山 淳平',
                'name_kana' =>  'たにやま じゅんぺい',
                'email' =>  'junpei_taniyama@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '川口 篤志',
                'name_kana' =>  'かわぐち あつし',
                'email' =>  'kawaguchi_331@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '田川 久美子',
                'name_kana' =>  'たがわ くみこ',
                'email' =>  'kumiko_tagawa@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '高野 豊',
                'name_kana' =>  'たかの ゆたか',
                'email' =>  'takanoyutaka@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '山田 秀一',
                'name_kana' =>  'やまだ しゅういち',
                'email' =>  'yamada_shuichi@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '谷 久美子',
                'name_kana' =>  'たに くみこ',
                'email' =>  'tani_89@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '中村 拓也',
                'name_kana' =>  'なかむら たくや',
                'email' =>  'nakamura14@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '前川 一俊',
                'name_kana' =>  'まえかわ かずとし',
                'email' =>  'maekawa_kazutoshi@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '三原 寛光',
                'name_kana' =>  'みはら ひろみつ',
                'email' =>  'miharahiromitsu@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '平松 晶子',
                'name_kana' =>  'ひらまつ しょうこ',
                'email' =>  'akiko_hiramatsu@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '小林 朋恵',
                'name_kana' =>  'こばやし ともえ',
                'email' =>  'kobayashi_tomoe@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '藤原 恵美子',
                'name_kana' =>  'ふじわら えみこ',
                'email' =>  'fujiwara_1222@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '白岩 秀樹',
                'name_kana' =>  'しらいわ ひでき',
                'email' =>  'shiraiwa_91@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '神谷 智博',
                'name_kana' =>  'かみや ともひろ',
                'email' =>  'kamiya_88@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '松嶋 洋史',
                'name_kana' =>  'まつしま ひろふみ',
                'email' =>  'matsushimahiroshi@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '津曲 真理子',
                'name_kana' =>  'つまがり まりこ',
                'email' =>  'tsumagari_mariko@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '澤田 友一',
                'name_kana' =>  'さわだ ともかず',
                'email' =>  'yuichi_sawada@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '渡辺 裕佑',
                'name_kana' =>  'わたなべ ゆうすけ',
                'email' =>  'watanabeyusuke@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '桜井 由美子',
                'name_kana' =>  'さくらい ゆみこ',
                'email' =>  'yumikosakurai@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '小林 真紀',
                'name_kana' =>  'こばやし まき',
                'email' =>  'kobayashi_maki@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '酒井 愛子',
                'name_kana' =>  'さかい あいこ',
                'email' =>  'sakai_416@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '関根 梓',
                'name_kana' =>  'せきね あずさ',
                'email' =>  'sekine_1112@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '鈴木 友美',
                'name_kana' =>  'すずき ゆみ',
                'email' =>  'tomomi_suzuki@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '小島 孝司',
                'name_kana' =>  'こじま こうじ',
                'email' =>  'kojima_takashi@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '武藤 桂子',
                'name_kana' =>  'むとう けいこ',
                'email' =>  'muto_keiko@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '橋本 直之',
                'name_kana' =>  'はしもと ただゆき',
                'email' =>  'naoyukihashimoto@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '黒澤 英里',
                'name_kana' =>  'くろさわ えり',
                'email' =>  'kurosawa_eri@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '車 拓',
                'name_kana' =>  'くるま たく',
                'email' =>  'kuruma516@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '櫻井 崇史',
                'name_kana' =>  'さくらい たかし',
                'email' =>  'takashi_sakurai@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '松浦 美幸',
                'name_kana' =>  'まつうら みゆき',
                'email' =>  'matsuuramiyuki@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '泉 聡',
                'name_kana' =>  'いずみ あきら',
                'email' =>  'satoshi_izumi@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '江崎 奈津美',
                'name_kana' =>  'えざき なつみ',
                'email' =>  'natsumiezaki@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '萩野 学',
                'name_kana' =>  'はぎの まなぶ',
                'email' =>  'haginomanabu@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '徳永 麻紀',
                'name_kana' =>  'とくなが まき',
                'email' =>  'tokunaga_maki@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '岡田 晴加',
                'name_kana' =>  'おかだ はるか',
                'email' =>  'okada_haruka@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '安藤 孝夫',
                'name_kana' =>  'あんどう たかお',
                'email' =>  'ando_takao@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '山本 理子',
                'name_kana' =>  'やまもと りこ',
                'email' =>  'yamamotoriko@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '白石 史成',
                'name_kana' =>  'しらいし ふみなり',
                'email' =>  'fuminarishiraishi@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '野尻 和枝',
                'name_kana' =>  'のじり かずえ',
                'email' =>  'kazuenojiri@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '斎藤 功',
                'name_kana' =>  'さいとう いさお',
                'email' =>  'saitoisao@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '後藤 晋太郎',
                'name_kana' =>  'ごとう しんたろう',
                'email' =>  'goto1129@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '浅田 和洋',
                'name_kana' =>  'あさだ かずひろ',
                'email' =>  'asada_131@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '田渕 賢一',
                'name_kana' =>  'たぶち けんいち',
                'email' =>  'kenichi_tabuchi@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '村松 利恵',
                'name_kana' =>  'むらまつ りえ',
                'email' =>  'muramatsu_1210@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '菅原 隆介',
                'name_kana' =>  'すがわら りゅうすけ',
                'email' =>  'sugawara121@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '本間 智津子',
                'name_kana' =>  'ほんま ちづこ',
                'email' =>  'honma54@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '梅本 啓',
                'name_kana' =>  'うめもと けい',
                'email' =>  'kei_umemoto@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '寺田 駿',
                'name_kana' =>  'てらだ しゅん',
                'email' =>  'terada_shun@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '伊藤 勇二',
                'name_kana' =>  'いとう ゆうじ',
                'email' =>  'yujiito@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '渡部 雅大',
                'name_kana' =>  'わたなべ まさひろ',
                'email' =>  'masahiro_watanabe@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '中嶋 哲治',
                'name_kana' =>  'なかじま てつじ',
                'email' =>  'tetsujinakajima@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '木村 ちあき',
                'name_kana' =>  'きむら ちあき',
                'email' =>  'kimura_chiaki@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '大内 修一',
                'name_kana' =>  'おおうち しゅういち',
                'email' =>  'ouchi1227@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '栗原 俊彦',
                'name_kana' =>  'くりはら としひこ',
                'email' =>  'kurihara118@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '川崎 美和',
                'name_kana' =>  'かわさき みわ',
                'email' =>  'kawasaki_miwa@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '竹川 剛',
                'name_kana' =>  'たけかわ つよし',
                'email' =>  'takekawa63@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '高橋 新',
                'name_kana' =>  'たかはし しん',
                'email' =>  'aratatakahashi@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '佐々木 崇',
                'name_kana' =>  'ささき たかし',
                'email' =>  'sasakitakashi@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '木曽 南美',
                'name_kana' =>  'きそ みなみ',
                'email' =>  'minamikiso@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '多田 薫',
                'name_kana' =>  'ただ かおる',
                'email' =>  'tadakaoru@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '佐藤 正弘',
                'name_kana' =>  'さとう まさひろ',
                'email' =>  'masahiro_sato@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '伊藤 太一郎',
                'name_kana' =>  'いとう たいちろう',
                'email' =>  'itotaichiro@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '横山 憲',
                'name_kana' =>  'よこやま ただし',
                'email' =>  'yokoyama_116@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '杉浦 徳彦',
                'name_kana' =>  'すぎうら のりひこ',
                'email' =>  'sugiura_328@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '田中 征志',
                'name_kana' =>  'たなか まさし',
                'email' =>  'masashitanaka@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '小澤 泰幸',
                'name_kana' =>  'おざわ やすゆき',
                'email' =>  'yasuyuki_ozawa@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '栗原 圭',
                'name_kana' =>  'くりはら けい',
                'email' =>  'kuriharakei@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '鈴木 佳奈',
                'name_kana' =>  'すずき かな',
                'email' =>  'kanasuzuki@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '朝山 弥生',
                'name_kana' =>  'あさやま やよい',
                'email' =>  'asayama_311@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '橋本 賢司',
                'name_kana' =>  'はしもと けんじ',
                'email' =>  'hashimoto_kenji@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '森本 文男',
                'name_kana' =>  'もりもと ふみお',
                'email' =>  'fumiomorimoto@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '池田 愛',
                'name_kana' =>  'いけだ あい',
                'email' =>  'ikedaai@example.com',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '長浜 真紀子',
                'name_kana' =>  'ながはま まきこ',
                'email' =>  'makikonagahama@example.org',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '稲田 和之',
                'name_kana' =>  'いなだ かずゆき',
                'email' =>  'inada_58@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '尾本 翔子',
                'name_kana' =>  'おもと しょうこ',
                'email' =>  'shoko_omoto@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '原田 克俊',
                'name_kana' =>  'はらだ かつとし',
                'email' =>  'katsutoshiharada@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '大井 由衣',
                'name_kana' =>  'おおい ゆい',
                'email' =>  'yui_oi@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '原田 文崇',
                'name_kana' =>  'はらだ ふみたか',
                'email' =>  'harada_910@example.ne.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '荒川 一博',
                'name_kana' =>  'あらかわ かずひろ',
                'email' =>  'kazuhiro_arakawa@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '黒田 裕之',
                'name_kana' =>  'くろだ ひろゆき',
                'email' =>  'kuroda_hiroyuki@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '板山 さやか',
                'name_kana' =>  'いたやま さやか',
                'email' =>  'itayama1231@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '小野塚 和弘',
                'name_kana' =>  'おのづか かずひろ',
                'email' =>  'kazuhiroonozuka@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '志田 大輔',
                'name_kana' =>  'しだ だいすけ',
                'email' =>  'daisuke_shida@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '天野 ひろこ',
                'name_kana' =>  'あまの ひろこ',
                'email' =>  'hiroko_amano@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '木村 忍',
                'name_kana' =>  'きむら しのぶ',
                'email' =>  'kimura1222@example.co.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '菅原 忠',
                'name_kana' =>  'すがわら ただし',
                'email' =>  'sugawaratadashi@example.jp',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],
            [
                'name' =>  '大西 智子',
                'name_kana' =>  'おおにし ともこ',
                'email' =>  'onishi_tomoko@example.net',
                'password' => Hash::make('password'),
                'created_at' => new DateTime(),
                'updated_at' => new DateTime(),
            ],                        
        ]);
    }
}
